# This is a basic workflow to help you get started with Actions

name: my github action
env: 
   APP_NAME: "MY_tst" 
   PKG_NAME: "deploy_smth_ver-${{ github.sha }}"
   
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Exec commnd
        run: |
          echo  "Hi 1"
          echo "Hi 2 ${{ env.APP_NAME }}"
          echo "Hi 3 ${{ env.PKG_NAME }}"
      - name: git clone repo
        uses: actions/checkout@v1
      - name: list current folder
        run: ls -la 
      - name: test pkgs
        run: ansible --version
      - name: zzzzip
        run: zip
       
  my_testing2:
     runs-on: ubuntu-latest
     needs: [my_testing]
     env:
        VAR1: "this var1"
        VAR2: "This var2"
     steps: 
      - name: second
        run:  echo "$LOCAL_VAR"
     
      - name: third
        run:  echo "1= ${{ env.VAR1 }}"
        
        env:
          LOCAL_VAR: " this local"
          
